{
	"dataType": "CVE_RECORD",
	"dataVersion": "5.0",
	"cveMetadata": {
		"cveId": "CVE-2020-27619",
		"assignerOrgId": "d6c1279f-00f6-4ef7-9217-f89ffe703ec0",
		"assignerShortName": "palo_alto",
		"state": "PUBLISHED",
		"datePublished": "2021-02-10T00:00:00",
		"dateUpdated": "2021-02-10T00:00:00.000000Z",
		"dateReserved": "2021-02-10T00:00:00"
	},
	"containers": {
		"cna": {
			"providerMetadata": {
				"orgID": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
				"shortName": "mitre",
				"dateUpdated": "2024-02-03T07:06:28.299004"
			},
			"title": "Informational: Impact of Python Test Suite Vulnerability CVE-2020-27619",
			"descriptions": [
				{
					"lang": "en",
					"value": "The Palo Alto Networks Product Security Assurance team evaluated the Python test suite vulnerability CVE-2020-27619.\n\nThere are no scenarios that enable successful exploitation of the vulnerability in Cortex XSOAR or PAN-OS software. No product release contains the Python test suite that is necessary to exploit this vulnerability. As a result, there is no known security impact for this vulnerability in Cortex XSOAR or PAN-OS software.\n",
					"supportingMedia": [
						{
							"base64": "false",
							"type": "text/html",
							"value": "<pre>The Palo Alto Networks Product Security Assurance team evaluated the Python test suite vulnerability CVE-2020-27619.\n\nThere are no scenarios that enable successful exploitation of the vulnerability in Cortex XSOAR or PAN-OS software. No product release contains the Python test suite that is necessary to exploit this vulnerability. As a result, there is no known security impact for this vulnerability in Cortex XSOAR or PAN-OS software.\n</pre>"
						}
					]
				}
			],
			"affected": [
				{
					"vendor": "Palo Alto Networks",
					"product": "Cortex XSOAR",
					"versions": [
						{
							"status": "unaffected",
							"version": "All"
						}
					]
				},
				{
					"vendor": "Palo Alto Networks",
					"product": "PAN-OS",
					"versions": [
						{
							"status": "unaffected",
							"version": "All"
						}
					]
				}
			],
			"metrics": [
				{
					"format": "CVSS",
					"scenarios": [
						{
							"lang": "en",
							"value": "GENERAL"
						}
					],
					"cvssV3_1": {
						"version": "3.1",
						"vectorString": "CVSS:3.1/AV:P/AC:H/PR:H/UI:R/S:U/C:N/I:N/A:N",
						"attackVector": "PHYSICAL",
						"attackComplexity": "HIGH",
						"privilegesRequired": "HIGH",
						"userInteraction": "REQUIRED",
						"scope": "UNCHANGED",
						"confidentialityImpact": "NONE",
						"integrityImpact": "NONE",
						"availabilityImpact": "NONE",
						"baseScore": 0,
						"baseSeverity": "NONE"
					}
				}
			],
			"solutions": [
				{
					"lang": "en",
					"value": "No Palo Alto Networks Cortex XSOAR or PAN-OS product updates are required.",
					"supportingMedia": {
						"base64": false,
						"type": "text/html",
						"value": "No Palo Alto Networks Cortex XSOAR or PAN-OS product updates are required."
					}
				}
			],
			"references": [
				{
					"tags": [
						"x_refsource_CONFIRM"
					],
					"url": "https://security.paloaltonetworks.com/PAN-SA-2021-02"
				},
				{
					"tags": [
						"x_refsource_CONFIRM"
					],
					"url": "https://nvd.nist.gov/vuln/detail/CVE-2020-27619"
				},
				{
					"tags": [
						"x_refsource_CONFIRM"
					],
					"url": "https://bugs.python.org/issue41944"
				}
			],
			"timeline": [
				{
					"time": "2021-02-10T17:00:00.000Z",
					"lang": "eng",
					"value": "Initial publication"
				}
			],
			"source": {
				"discovery": "EXTERNAL"
			},
			"datePublic": "2021-02-10T17:00:00.000Z",
			"x_generator": {
				"engine": "Vulnogram 0.0.9"
			}
		}
	}
}
